// <auto-generated />
using GestaoAcademica.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GestaoAcademica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512000000_AdicionarCursoDisciplina")]
    partial class AdicionarCursoDisciplina
    {
    }
}
