// <auto-generated />
using System;
using GestaoAcademica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoAcademica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestaoAcademica.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Alunos");

                    // Dados estaticos para teste
                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CursoId = 1,
                            DataNascimento = new DateOnly(2008, 3, 17),
                            Email = "viniciuscorreia@academico.local",
                            Matricula = "20260002",
                            Nome = "Vinicius Correia"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = false,
                            CursoId = 2,
                            DataNascimento = new DateOnly(2002, 4, 12),
                            Email = "ana.souza@academico.local",
                            Matricula = "20260001",
                            Nome = "Ana Souza"
                        }
                    );
                });

            modelBuilder.Entity("GestaoAcademica.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("DuracaoSemestres")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Cursos");

                    // Dados estaticos para teste
                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "ADS",
                            DuracaoSemestres = 5,
                            Nome = "Analise e Desenvolvimento de Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "SI",
                            DuracaoSemestres = 8,
                            Nome = "Sistemas de Informacao"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "CC",
                            DuracaoSemestres = 8,
                            Nome = "Ciencia da Computacao"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "ES",
                            DuracaoSemestres = 8,
                            Nome = "Engenharia de Software"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "SEG",
                            DuracaoSemestres = 6,
                            Nome = "Seguranca da Informacao"
                        }
                    );
                });

            modelBuilder.Entity("GestaoAcademica.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CursoId");

                    b.ToTable("Disciplinas");

                    // Dados estaticos para teste
                    b.HasData(
                        // ===== ADS (CursoId = 1) =====
                        new
                        {
                            Id = 1,
                            CargaHoraria = 80,
                            Codigo = "ADS101",
                            Nome = "Algoritmos e Logica de Programacao",
                            CursoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 80,
                            Codigo = "ADS102",
                            Nome = "Estrutura de Dados",
                            CursoId = 1
                        },

                        // ===== Sistemas de Informacao (CursoId = 2) =====
                        new
                        {
                            Id = 3,
                            CargaHoraria = 80,
                            Codigo = "SI101",
                            Nome = "Analise de Sistemas",
                            CursoId = 2
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 80,
                            Codigo = "SI102",
                            Nome = "Gestao de Projetos",
                            CursoId = 2
                        },

                        // ===== Ciencia da Computacao (CursoId = 3) =====
                        new
                        {
                            Id = 5,
                            CargaHoraria = 80,
                            Codigo = "CC101",
                            Nome = "Calculo I",
                            CursoId = 3
                        },
                        new
                        {
                            Id = 6,
                            CargaHoraria = 80,
                            Codigo = "CC102",
                            Nome = "Teoria da Computacao",
                            CursoId = 3
                        },

                        // ===== Engenharia de Software (CursoId = 4) =====
                        new
                        {
                            Id = 7,
                            CargaHoraria = 80,
                            Codigo = "ES101",
                            Nome = "Arquitetura de Software",
                            CursoId = 4
                        },
                        new
                        {
                            Id = 8,
                            CargaHoraria = 80,
                            Codigo = "ES102",
                            Nome = "Testes de Software",
                            CursoId = 4
                        },

                        // ===== Seguranca da Informacao (CursoId = 5) =====
                        new
                        {
                            Id = 9,
                            CargaHoraria = 80,
                            Codigo = "SEG101",
                            Nome = "Criptografia",
                            CursoId = 5
                        },
                        new
                        {
                            Id = 10,
                            CargaHoraria = 80,
                            Codigo = "SEG102",
                            Nome = "Seguranca de Redes",
                            CursoId = 5
                        }
                    );
                });

            modelBuilder.Entity("GestaoAcademica.Models.MatriculaDisciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("AlunoId", "DisciplinaId")
                        .IsUnique();

                    b.ToTable("MatriculasDisciplinas");
                });

            modelBuilder.Entity("GestaoAcademica.Models.Aluno", b =>
                {
                    b.HasOne("GestaoAcademica.Models.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("GestaoAcademica.Models.Disciplina", b =>
                {
                    b.HasOne("GestaoAcademica.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("GestaoAcademica.Models.MatriculaDisciplina", b =>
                {
                    b.HasOne("GestaoAcademica.Models.Aluno", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAcademica.Models.Disciplina", "Disciplina")
                        .WithMany("Matriculas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("GestaoAcademica.Models.Aluno", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("GestaoAcademica.Models.Curso", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Disciplinas");
                });

            modelBuilder.Entity("GestaoAcademica.Models.Disciplina", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
